api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Entity/resources.yaml']
    graphql:
            enabled: true
            graphiql:
                enabled: true
