api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']



    # The title of the API.
    title:                'my super api'

    # The description of the API.
    description:          'and here comes the description'

